version: '3.8'

services:
  # 1. GATEWAY: Menerima trafik HTTP dan WebAuthn
  gateway:
    image: php:8.3-cli
    container_name: hki_gateway
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    command: >
      bash -c "apt-get update && apt-get install -y libzip-dev zip unzip
      && docker-php-ext-install pdo pdo_mysql zip
      && php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      - mysql
      - redis
      - rabbitmq
    networks:
      - hki_network
    restart: unless-stopped

  # 2. WORKER: Mesin komputasi Hash Chaining di latar belakang
  worker:
    image: php:8.3-cli
    container_name: hki_log_worker
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: >
      bash -c "apt-get update && apt-get install -y libzip-dev zip unzip
      && docker-php-ext-install pdo pdo_mysql zip
      && php artisan queue:work rabbitmq --sleep=1 --tries=3"
    depends_on:
      - mysql
      - redis
      - rabbitmq
    networks:
      - hki_network
    restart: unless-stopped_ga

  # 3. DATABASE: Penyimpanan persisten (Master Table & Audit Logs)
  mysql:
    image: mysql:8.0
    container_name: hki_mysql
    restart: always
    environment:
      MYSQL_DATABASE: hki_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: hki_user
      MYSQL_PASSWORD: hkipassword
    ports:
      - "3306:3306"
    volumes:
      - hki_mysql_data:/var/lib/mysql
    networks:
      - hki_network

  # 4. CACHE & STATE: Penyimpanan Global State Anchor yang volatil dan super cepat
  redis:
    image: redis:alpine
    container_name: hki_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - hki_redis_data:/data
    networks:
      - hki_network

  # 5. MESSAGE BROKER: Jembatan antrean untuk mencegah peladen meledak
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: hki_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # Port komunikasi data AMQP
      - "15672:15672" # Port antarmuka dasbor web manajemen
    volumes:
      - hki_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - hki_network

volumes:
  hki_mysql_data:
  hki_redis_data:
  hki_rabbitmq_data:

networks:
  hki_network:
    driver: bridge