<?php

use App\Models\HKIProposal;
use App\Models\HKIType;
use App\Models\User;
use App\Services\HKI\AuditLogService;
use Illuminate\Support\Str;

$auditLogService = app(AuditLogService::class);
$users = User::pluck('id')->toArray();
$hkiTypes = HKIType::pluck('id')->toArray();

if (empty($users) || empty($hkiTypes)) {
    echo "Database harus memiliki minimal 1 User dan 1 Jenis HKI.\n";
    exit;
}

$count = 30;

echo "Memulai pembuatan $count proposal baru beserta Audit Log-nya...\n";

for ($i = 1; $i <= $count; $i++) {
    $userId = $users[array_rand($users)];
    $typeId = $hkiTypes[array_rand($hkiTypes)];
    
    // Coba create proposal
    $proposal = HKIProposal::create([
        'user_id' => $userId,
        'hki_type_id' => $typeId,
        'title' => 'Proposal Dummy Skripsi Ke-' . $i . ' (' . Str::random(5) . ')',
        'description' => 'Data otomatis ini ditambahkan untuk keperluan pengujian performa tabel dan pembuktian kekuatan komputasi hash chain.',
        'status' => 'SUBMITTED',
        'publication_country' => 'ID',
        'publication_city' => 'Sumedang',
        'url_detail' => '-',
        'publication_date' => now()->subDays(rand(1, 60))->format('Y-m-d'),
    ]);

    // Masukkan ke Audit Log dan Kalkulasi Hash secara otomatis menggunakan Service
    $auditLogService->logActivityGlobal([
        'model_type' => HKIProposal::class,
        'model_id' => $proposal->id,
        'user_id' => $userId,
        'action' => 'Pengajuan proposal baru (Auto-Seeder)',
        'payload' => [
            'title' => $proposal->title,
            'hki_type_id' => $proposal->hki_type_id,
            'status' => $proposal->status,
            'note' => 'Generated by System'
        ],
        'digital_signature' => null,
    ]);

    echo "[$i/$count] Berhasil membuat proposal: {$proposal->title}\n";
}

echo "\nSelesai! $count Proposal berhasil ditambahkan dan Rantai Hash Global tetap tersinkronisasi.\n";
